from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetAllPerfiles200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nombre_perfil=None, imagen_perfil=None, favoritos_perfil=None):  # noqa: E501
        """GetAllPerfiles200ResponseInner - a model defined in OpenAPI

        :param nombre_perfil: The nombre_perfil of this GetAllPerfiles200ResponseInner.  # noqa: E501
        :type nombre_perfil: str
        :param imagen_perfil: The imagen_perfil of this GetAllPerfiles200ResponseInner.  # noqa: E501
        :type imagen_perfil: List[str]
        :param favoritos_perfil: The favoritos_perfil of this GetAllPerfiles200ResponseInner.  # noqa: E501
        :type favoritos_perfil: List[int]
        """
        self.openapi_types = {
            'nombre_perfil': str,
            'imagen_perfil': List[str],
            'favoritos_perfil': List[int]
        }

        self.attribute_map = {
            'nombre_perfil': 'nombrePerfil',
            'imagen_perfil': 'imagenPerfil',
            'favoritos_perfil': 'favoritosPerfil'
        }

        self._nombre_perfil = nombre_perfil
        self._imagen_perfil = imagen_perfil
        self._favoritos_perfil = favoritos_perfil

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllPerfiles200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAllPerfiles_200_response_inner of this GetAllPerfiles200ResponseInner.  # noqa: E501
        :rtype: GetAllPerfiles200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombre_perfil(self) -> str:
        """Gets the nombre_perfil of this GetAllPerfiles200ResponseInner.

        Nombre con el cual se identificará el perfil. Este nombre no podrá ser el mismo para dos perfiles pertenecientes a la misma cuenta  # noqa: E501

        :return: The nombre_perfil of this GetAllPerfiles200ResponseInner.
        :rtype: str
        """
        return self._nombre_perfil

    @nombre_perfil.setter
    def nombre_perfil(self, nombre_perfil: str):
        """Sets the nombre_perfil of this GetAllPerfiles200ResponseInner.

        Nombre con el cual se identificará el perfil. Este nombre no podrá ser el mismo para dos perfiles pertenecientes a la misma cuenta  # noqa: E501

        :param nombre_perfil: The nombre_perfil of this GetAllPerfiles200ResponseInner.
        :type nombre_perfil: str
        """

        self._nombre_perfil = nombre_perfil

    @property
    def imagen_perfil(self) -> List[str]:
        """Gets the imagen_perfil of this GetAllPerfiles200ResponseInner.

        Fotografía representativa del perfil  # noqa: E501

        :return: The imagen_perfil of this GetAllPerfiles200ResponseInner.
        :rtype: List[str]
        """
        return self._imagen_perfil

    @imagen_perfil.setter
    def imagen_perfil(self, imagen_perfil: List[str]):
        """Sets the imagen_perfil of this GetAllPerfiles200ResponseInner.

        Fotografía representativa del perfil  # noqa: E501

        :param imagen_perfil: The imagen_perfil of this GetAllPerfiles200ResponseInner.
        :type imagen_perfil: List[str]
        """

        self._imagen_perfil = imagen_perfil

    @property
    def favoritos_perfil(self) -> List[int]:
        """Gets the favoritos_perfil of this GetAllPerfiles200ResponseInner.

        Representa la lista de contenidos multimedia de la aplicacion que la persona que utiliza el perfil ha marcado como favoritos. Este array almacenará únicamente el identificador de dichos contenidos con el fin de simplificar y facilitar la implementación de la aplicación.  # noqa: E501

        :return: The favoritos_perfil of this GetAllPerfiles200ResponseInner.
        :rtype: List[int]
        """
        return self._favoritos_perfil

    @favoritos_perfil.setter
    def favoritos_perfil(self, favoritos_perfil: List[int]):
        """Sets the favoritos_perfil of this GetAllPerfiles200ResponseInner.

        Representa la lista de contenidos multimedia de la aplicacion que la persona que utiliza el perfil ha marcado como favoritos. Este array almacenará únicamente el identificador de dichos contenidos con el fin de simplificar y facilitar la implementación de la aplicación.  # noqa: E501

        :param favoritos_perfil: The favoritos_perfil of this GetAllPerfiles200ResponseInner.
        :type favoritos_perfil: List[int]
        """

        self._favoritos_perfil = favoritos_perfil
